defaults: &defaults
  working_directory: /nerves/build
  docker:
    - image: nervesproject/nerves:1.3.0
  environment:
    ELIXIR_VERSION: 1.6.6

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
      unzip -d /usr/local/elixir Precompiled.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV
install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force
install_nerves_bootstrap: &install_nerves_bootstrap
  run:
    name: Install nerves_bootstrap
    command: |
      mix archive.install hex nerves_bootstrap "~> 1.0" --force
install_ghr: &install_ghr
  run:
    name: Install ghr (Github Releases)
    command: |
      wget https://github.com/tcnksm/ghr/releases/download/v0.9.0/ghr_v0.9.0_linux_amd64.tar.gz
      tar xf ghr_v0.9.0_linux_amd64.tar.gz
      ln -sf ghr_v0.9.0_linux_amd64/ghr .


version: 2.0

jobs:
  test_farmbot_core:
    <<: *defaults
    environment:
      MIX_ENV: test
      MIX_TARGET: host
      NERVES_LOG_DISABLE_PROGRESS_BAR: "yes"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
        keys:
          - v1-fbcore-dependency-cache-{{ checksum "farmbot_core/mix.lock" }}
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - run:
        name: Test Farmbot Core
        command: make farmbot_os_test
      - save_cache:
        key: - v1-fbcore-dependency-cache-{{ checksum "farmbot_core/mix.lock" }}
        paths:
          - farmbot_core/_build
          - farmbot_core/deps

  test_farmbot_ext:
    <<: *defaults
    environment:
      MIX_ENV: test
      MIX_TARGET: host
      NERVES_LOG_DISABLE_PROGRESS_BAR: "yes"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
        keys:
          - v1-fbext-dependency-cache-{{ checksum "farmbot_ext/mix.lock" }}
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - run:
        name: Test Farmbot Ext
        command: make farmbot_ext_test
      - save_cache:
        key: - v1-fbext-dependency-cache-{{ checksum "farmbot_ext/mix.lock" }}
        paths:
          - farmbot_ext/_build
          - farmbot_ext/deps

  test_farmbot_os:
    <<: *defaults
    environment:
      MIX_ENV: test
      MIX_TARGET: host
      NERVES_LOG_DISABLE_PROGRESS_BAR: "yes"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
        keys:
          - v1-fbos-host-dependency-cache-{{ checksum "farmbot_os/mix.lock.host" }}
      - <<: *install_elixir
      - <<: *install_hex_rebar
      - <<: *install_nerves_bootstrap
      - run:
        name: Test Farmbot OS
        command: make farmbot_os_test
      - save_cache:
        key: - v1-fbos-host-dependency-cache-{{ checksum "farmbot_os/mix.lock" }}
        paths:
          - farmbot_os/_build
          - farmbot_os/deps
workflows:
  version: 2
  test:
    jobs:
      - test_farmbot_core:
        context: org-global
      - test_farmbot_ext:
        context: org-global
      - test_farmbot_os:
        context: org-global
